name    'pushstack-pacemaker'
version '0.1.0'
source 'https://github.com/pushstack/puppet-pacemaker'
author 'pushstack'
license 'Apache License, Version 2.0'
summary 'Puppet module to provide configuration managent of pacemaker and associated resources'
description 'Puppet module to provide configuration managent of pacemaker and associated resources'
project_page 'https://github.com/pushstack/puppet-pacemaker'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
dependency 'puppetlabs/stdlib'
dependency 'puppetlabs/firewall'
